Repository P1Z7/frontend, pull requests merged in 2024-01, with the labels that each got.

#1 ✨feat : 로그인 로직 구현
  app/(route)/signin/layout.tsx
  app/(route)/signin/page.tsx
  app/_providers/AuthProvider.tsx
  app/_utils/signValidate.ts
  app/api/auth/[...nextauth]/route.ts
  package-lock.json
  package.json
  public/icons/icon-leftarrow.svg
  tsconfig.json
Labels: ✨feat

#2 ✨ feat: signup page 기능 및 UI 로직 구현
  .vscode/settings.json
  app/(route)/signup/components/AccountInfo.tsx
  app/(route)/signup/components/GenericForm.tsx
  app/(route)/signup/components/InputContainer.tsx
  app/(route)/signup/components/MyArtistsInfo.tsx
  app/(route)/signup/components/ProfileInfo.tsx
  app/(route)/signup/components/ProfileSetup.tsx
  app/(route)/signup/page.tsx
  app/_hooks/useFunnel.tsx
  app/_utils/signupValidation.ts
  package-lock.json
  package.json
  public/icons/add_image_gray.svg
  public/icons/arrow_back_black.svg
  public/icons/closed_eyes_black.svg
  public/icons/opened_eyes_black.svg
  public/icons/x_gray.svg
Labels: ✨feat

#5 ✨ feat: post 페이지 정보 저장 기능 구현
  app/(route)/post/_components/DetailInfo.tsx
  app/(route)/post/_components/MainInfo.tsx
  app/(route)/post/_components/StarInfo.tsx
  app/(route)/post/_components/SubInfo.tsx
  app/(route)/post/page.tsx
  app/_components/Dropdown/Dropdown.tsx
  app/_components/Modal/AddressModal/AddressModal.tsx
  app/_components/Modal/CalendarModal/CalendarModal.tsx
  app/_components/Modal/ModalFrame.tsx
  app/_components/Modal/ModalPortal.tsx
  app/_components/Tag/GiftTag/GiftTag.tsx
  app/_store/index.ts
  app/_store/slice/modalSlice.ts
  app/_store/slice/postSlice.ts
  app/layout.tsx
  next.config.mjs
  package-lock.json
  package.json
  tailwind.config.ts
Labels: ✨feat

#9 ✨feat : Input 공통컴포넌트
  app/(route)/setting/profile/page.tsx
  app/(route)/signup/_components/AccountInfo.tsx
  app/_components/input/InputFile.tsx
  app/_components/input/InputText.tsx
Labels: ✨feat

#11 ⚡️ hotfix: InputFile
  app/(route)/setting/profile/page.tsx
  app/_components/input/InputFile.tsx
  app/_components/input/InputText.tsx
Labels: ⚡️fix

#14 ⚡️ hotfix (Input) : children을 optional prop으로
  app/_components/input/InputFile.tsx
  app/_components/input/InputText.tsx
Labels: ⚡️fix

#15 ⚡️fix: signup 페이지 pr 리뷰 반영, stpe3 모달 추가
  app/(route)/post/_components/DetailInfo.tsx
  app/(route)/setting/favorite/page.tsx
  app/(route)/signup/_components/GenericForm.tsx
  app/(route)/signup/_components/InputContainer.tsx
  app/(route)/signup/_components/MyArtistsInfo.tsx
  app/(route)/signup/_components/ProfileInfo.tsx
  app/(route)/signup/_components/ProfileSetup.tsx
  app/(route)/signup/_components/step/AccountInfo.tsx
  app/(route)/signup/_components/step/MyArtistsInfo.tsx
  app/(route)/signup/_components/step/ProfileInfo.tsx
  app/(route)/signup/page.tsx
  app/_components/modal/ReqNewArtistModal.tsx
  app/_hooks/useFunnel.tsx
  app/_types/index.ts
  app/layout.tsx
  package-lock.json
  package.json
Labels: ⚡️fix

#16 ♻️ refactor: post 페이지 input 리팩토링
  app/(route)/post/_components/DetailInfo.tsx
  app/(route)/post/_components/FunnelTitle.tsx
  app/(route)/post/_components/MainInfo.tsx
  app/(route)/post/_components/PostFooter.tsx
  app/(route)/post/_components/StarInfo.tsx
  app/(route)/post/_components/SubInfo.tsx
  app/(route)/post/page.tsx
  app/(route)/signup/_components/GenericForm.tsx
  app/_components/Dropdown.tsx
  app/_components/ProgressBar.tsx
  app/_components/bottom-sheet/StarBottomSheet.tsx
  app/_components/card/ArtistProfile.tsx
  app/_components/input/InputFile.tsx
  app/_components/input/InputText.tsx
  app/_components/input/SearchInput.tsx
  app/_components/modal/AddressModal.tsx
  app/_components/modal/CalendarModal.tsx
  app/_components/modal/ModalFrame.tsx
  app/_hooks/useFunnel.tsx
  app/_types/index.ts
  tailwind.config.ts
Labels: ♻️ refactor

#19 ✨ feat: /signup 검색 기능 추가
  app/(route)/setting/favorite/page.tsx
  app/(route)/signup/_components/ArtistCard.tsx
  app/(route)/signup/_components/ProfileSetup.tsx
  app/(route)/signup/_components/SearchArtist.tsx
  app/(route)/signup/_components/SignupFunnelTitle.tsx
  app/(route)/signup/_components/step/AccountInfo.tsx
  app/(route)/signup/_components/step/MyArtistsInfo.tsx
  app/(route)/signup/_components/step/ProfileInfo.tsx
  app/(route)/signup/page.tsx
Labels: ✨feat

#17 ✨ feat: 후기 작성 페이지 구현
  app/(route)/event/[id]/post/page.tsx
Labels: ✨feat, 🆗 merge

#21 ♻️Refactor: signin, setting 페이지 리액트훅폼 사용하기
  app/(route)/setting/_components/SettingHeader.tsx
  app/(route)/setting/favorite/page.tsx
  app/(route)/setting/password/page.tsx
  app/(route)/setting/profile/page.tsx
  app/(route)/signin/page.tsx
  app/(route)/signup/_components/step/AccountInfo.tsx
  app/_components/input/InputFile.tsx
  app/_components/input/InputText.tsx
  app/_hooks/useEnterNext.tsx
Labels: ♻️ refactor

#22 🩹 chore: 후기 작성 페이지 에러 메시지 상수화
  app/(route)/event/[id]/post/page.tsx
  app/_components/Review.tsx
Labels: 🆗 merge, 🩹 chore

#23 ✨ feat: calendar 구현
  app/(route)/_components/BottomNav.tsx
  app/(route)/_components/EventMockData.ts
  app/(route)/_components/NewestEvents.tsx
  app/(route)/_components/PopularEvents.tsx
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/(route)/_components/carousel/NewestEventsCarousel.tsx
  app/(route)/_components/carousel/PopularEventsCarousel.tsx
  app/(route)/mypage/_components/EventCalendar.tsx
  app/(route)/page.tsx
  app/_components/Carousel.tsx
  app/_components/artist-list/ArtistList.tsx
  app/_components/artist-list/ArtistProfile.tsx
  app/_components/card/EventCard.tsx
  package-lock.json
  package.json
Labels: ✨feat

#28 ✨ feat: my-artist-evnet 구현
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/(route)/_components/carousel/NewestEventsCarousel.tsx
  app/(route)/_components/carousel/PopularEventsCarousel.tsx
  app/(route)/my-artist-event/_components/MyArtistEvent.tsx
  app/(route)/my-artist-event/page.tsx
  app/(route)/mypage/_components/EventCalendar.tsx
  app/_components/Header.tsx
  app/_components/artist-list/ArtistList.tsx
  app/_components/artist-list/ProfileMockData.ts
  app/_components/card/Chip.tsx
  app/_components/card/EventCard.tsx
  app/_components/card/EventMockData.ts
  app/_components/card/HorizontalEventCard.tsx
  app/_components/card/VerticalEventCard.tsx
  app/_types/index.ts
Labels: ✨feat, 🆗 merge

#25 ✨ feat: /edit 페이지 로직 구현
  app/(route)/event/[id]/edit/_components/EditContent.tsx
  app/(route)/event/[id]/edit/page.tsx
  app/(route)/post/_components/DetailInfo.tsx
  app/(route)/post/_components/FunnelTitle.tsx
  app/(route)/post/_components/ImageSection.tsx
  app/(route)/post/_components/MainInfo.tsx
  app/(route)/post/_components/StarInfo.tsx
  app/(route)/post/_components/SubInfo.tsx
  app/(route)/post/_components/_inputs/DetailInput.tsx
  app/(route)/post/_components/_inputs/MainInput.tsx
  app/(route)/post/_components/_inputs/StarInput.tsx
  app/(route)/post/_components/_inputs/SubInput.tsx
  app/(route)/post/page.tsx
  app/_components/Dropdown.tsx
  app/_components/WarningCheck.tsx
  app/_components/input/InputArea.tsx
  app/_components/input/InputText.tsx
  app/_components/modal/AddressModal.tsx
  app/_components/modal/CalendarModal.tsx
  app/_components/modal/EditModal.tsx
  app/_store/index.ts
  app/_store/slice/warningSlice.ts
  app/_utils/editValidate.ts
Labels: ✨feat, 🚫 merge

#29 ✨ feat: 검색 페이지 UI 구현
  .prettierrc
  .vscode/settings.json
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/(route)/_components/carousel/NewestEventsCarousel.tsx
  app/(route)/_components/carousel/PopularEventsCarousel.tsx
  app/(route)/my-artist-event/_components/MyArtistEvent.tsx
  app/(route)/mypage/_components/EventCalendar.tsx
  app/(route)/search/page.tsx
  app/_components/bottom-sheet/BigRegionBottomSheet.tsx
  app/_components/bottom-sheet/BottomSheetFrame.tsx
  app/_components/bottom-sheet/CalendarBottomSheet.tsx
  app/_components/bottom-sheet/GiftsBottomSheet.tsx
  app/_components/bottom-sheet/SmallRegionBottomSheet.tsx
  app/_components/card/HorizontalEventCard.tsx
  app/_components/card/VerticalEventCard.tsx
  app/_constants/regions.ts
  app/_types/index.ts
  tsconfig.json
Labels: ✨feat, 🚫 merge

#30 ✨ feat: 디자인 시스템 적용
  app/globals.css
  public/font/pretendard/Pretendard-Black.subset.woff2
  public/font/pretendard/Pretendard-ExtraBold.subset.woff2
  public/font/pretendard/Pretendard-ExtraLight.subset.woff2
  public/font/pretendard/Pretendard-Light.subset.woff2
  public/font/pretendard/Pretendard-Thin.subset.woff2
  public/font/pretendard/font.css
  tailwind.config.ts
Labels: ✨feat

#32 🩹 chore: 아이콘 파일 추가 및 svg 컴포넌트 설정
  next.config.mjs
  package-lock.json
  package.json
  public/icon/add-content.svg
  public/icon/add.svg
  public/icon/adjust.svg
  public/icon/align.svg
  public/icon/arrow-down_lg.svg
  public/icon/arrow-down_sm.svg
  public/icon/arrow-left_lg.svg
  public/icon/arrow-left_sm.svg
  public/icon/arrow-right_lg.svg
  public/icon/arrow-right_sm.svg
  public/icon/arrow-up_lg.svg
  public/icon/arrow-up_sm.svg
  public/icon/calendar.svg
  public/icon/calender-check.svg
  public/icon/check.svg
  public/icon/close.svg
  public/icon/edit.svg
  public/icon/filter.svg
  public/icon/gift.svg
  public/icon/heart.svg
  public/icon/kebab.svg
  public/icon/link.svg
  public/icon/map.svg
  public/icon/pencil.svg
  public/icon/picture_rectangle.svg
  public/icon/picture_square.svg
  public/icon/search.svg
  public/icon/sort.svg
  public/icon/user.svg
Labels: 🩹 chore
