Repository P1Z7/frontend, pull requests merged in 2024-03, with the labels that each got.

#171 ✨ feat: 데스크탑 및 모바일 헤더 구현
  app/(route)/(bottom-nav)/layout.tsx
  app/(route)/_components/artist-list/ArtistList.tsx
  app/(route)/event/[eventId]/approve/[editId]/page.tsx
  app/(route)/event/[eventId]/approve/page.tsx
  app/(route)/event/[eventId]/edit/_components/EditContent.tsx
  app/(route)/event/[eventId]/edit/page.tsx
  app/(route)/event/[eventId]/page.tsx
  app/(route)/event/[eventId]/post/page.tsx
  app/(route)/my-artist-event/_components/MyArtistEvent.tsx
  app/(route)/my-artist-event/page.tsx
  app/(route)/mypage/_components/EventTabs.tsx
  app/(route)/mypage/_components/SettingList.tsx
  app/(route)/mypage/_components/UserProfile.tsx
  app/(route)/mypage/_components/tab/MyArtistTab.tsx
  app/(route)/mypage/_components/tab/MyCalendarTab/ChipButtons.tsx
  app/(route)/mypage/_components/tab/MyCalendarTab/FoldButton.tsx
  app/(route)/mypage/_components/tab/MyCalendarTab/MyCalendar.tsx
  app/(route)/mypage/_components/tab/MyCalendarTab/NoContentsInCalendar.tsx
  app/(route)/mypage/_components/tab/MyCalendarTab/index.tsx
  app/(route)/mypage/_components/tab/MyEventTab.tsx
  app/(route)/mypage/_components/tab/MyLocationTab/FilteringButton.tsx
  app/(route)/mypage/_components/tab/MyLocationTab/MapInfoBox.tsx
  app/(route)/mypage/_components/tab/MyLocationTab/MyKaKaoMap.tsx
  app/(route)/mypage/_components/tab/MyLocationTab/index.tsx
  app/(route)/mypage/_components/tab/MyReviewTab/MyReview.tsx
  app/(route)/mypage/_components/tab/MyReviewTab/index.tsx
  app/(route)/mypage/page.tsx
  app/(route)/oauth/callback/[provider]/page.tsx
  app/(route)/page.tsx
  app/(route)/post/_components/DetailInfo.tsx
  app/(route)/post/page.tsx
  app/(route)/search/_components/FilterButton.tsx
  app/(route)/search/_components/SortButton.tsx
  app/(route)/search/page.tsx
  app/(route)/setting/my-artist/page.tsx
  app/(route)/setting/password/page.tsx
  app/(route)/setting/profile/page.tsx
  app/(route)/signin/_components/Confetti.tsx
  app/(route)/signin/_components/FadingDot.tsx
  app/(route)/signin/_components/LoadingDot.tsx
  app/(route)/signin/page.tsx
  app/_components/BottomNav.tsx
  app/_components/MyArtistList.tsx
  app/_components/PageLoading.tsx
  app/_components/bottom-sheet/MyPageBottomSheet.tsx
  app/_components/bottom-sheet/content/ArtistContent.tsx
  app/_components/header/Header.tsx
  app/_components/header/MobileHeader.tsx
  app/_components/header/PcHeader.tsx
  app/_components/input/SearchInput.tsx
  app/layout.tsx
  public/icon/add.svg
  public/icon/hamburger.svg
  tailwind.config.ts
Labels: ✨feat

#172 ♻️ refactor & ✨ feat: 검색 페이지 리팩토링 및 추가 기능 구현
  app/(route)/_components/SearchBar.tsx
  app/(route)/page.tsx
  app/(route)/search/_components/ArtistList.tsx
  app/(route)/search/_components/ArtistProfile.tsx
  app/(route)/search/_components/EventList.tsx
  app/(route)/search/_components/Filter.tsx
  app/(route)/search/_components/FilterButton.tsx
  app/(route)/search/_components/StatusButton.tsx
  app/(route)/search/_hooks/useFetch.ts
  app/(route)/search/_hooks/useSearch.tsx
  app/(route)/search/_hooks/useShowOnScroll.ts
  app/(route)/search/page.tsx
  app/_components/bottom-sheet/CalendarBottomSheet.tsx
  app/_components/bottom-sheet/EventBottomSheet.tsx
  app/_components/bottom-sheet/GiftsBottomSheet.tsx
  app/_components/bottom-sheet/content/CalendarContent.tsx
  app/_components/header/MobileHeader.tsx
  app/_components/header/PcHeader.tsx
  app/_types/index.ts
  app/_types/queryType.ts
  public/icon/search.svg
Labels: ✨feat, ♻️ refactor

#182 🐛 bug: 디자인 버그 수정
  app/(route)/_components/SearchBar.tsx
  app/(route)/event/[eventId]/_components/Banner.tsx
  app/(route)/event/[eventId]/_components/tab/ReviewTab.tsx
  app/(route)/event/[eventId]/page.tsx
  app/(route)/my-artist-event/_components/MyArtistEvent.tsx
  app/(route)/search/_components/ArtistList.tsx
  app/(route)/signup/_components/SearchArtist.tsx
  app/_components/MyArtistList.tsx
  app/_components/Tabs.tsx
  app/_components/header/MobileHeader.tsx
  app/_hooks/useFetchGroupSolo.ts
  public/icon/logout.svg
Labels: 🐛 bug

#174 ✨feat: 카카오맵 그룹핑 및 행사유형 별 오버레이 아이콘 설정하기
  app/(route)/mypage/_components/tab/MyLocationTab/MyKaKaoMap.tsx
  app/_hooks/useKakaoMap.ts
  app/layout.tsx
  public/image/marker-ads.png
  public/image/marker-cafe.png
  public/image/marker-etc.png
  public/image/marker-flower.png
  public/image/marker-photo.png
  public/image/marker-screen.png
Labels: ✨feat

#181 💄design: 로그인 페이지, 404 페이지 디자인 수정
  app/(route)/signin/page.tsx
  app/not-found.tsx
  public/image/notfound.png
Labels: 💄design

#176 ✨ feat & 💄design : /signup, /reset-password
  app/(route)/reset-password/_components/ResetPasswordTitle.tsx
  app/(route)/reset-password/_components/ResetPwSetup.tsx
  app/(route)/reset-password/_components/step/AuthEmail.tsx
  app/(route)/reset-password/_components/step/SetNewPw.tsx
  app/(route)/reset-password/page.tsx
  app/(route)/signin/page.tsx
  app/(route)/signup/_components/ProfileSetup.tsx
  app/(route)/signup/_components/SearchArtist.tsx
  app/(route)/signup/_components/SignupFunnelTitle.tsx
  app/(route)/signup/_components/Term.tsx
  app/(route)/signup/_components/step/AccountInfo.tsx
  app/(route)/signup/_components/step/MyArtistsInfo.tsx
  app/(route)/signup/_components/step/ProfileInfo.tsx
  app/(route)/signup/_components/step/TermsAgreement.tsx
  app/(route)/signup/page.tsx
  app/_api/api.ts
  app/_components/GenericFormProvider.tsx
  app/_components/button/BottomButton.tsx
  app/_components/layout/DottedLayout.tsx
  app/_constants/metaTag.ts
  app/_constants/toast.ts
  app/_hooks/checkEnterNextButton.tsx
  app/_types/index.ts
  app/_types/postBodyType.ts
  app/_types/putBodyType.ts
  app/_utils/handleResetPwSubmit.ts
  app/_utils/signupValidation.ts
  public/icon/arrow-right_sm.svg
Labels: ✨feat, 🆗 merge

#185 ✨feat (아티스트 지도 페이지, 마이페이지 지도) : 자동 포커즈기능 (지도 ↔ 리스트)
  app/(route)/artist/[artistId]/_components/ArtistMap.tsx
  app/(route)/artist/[artistId]/_components/ChipButtons.tsx
  app/(route)/artist/[artistId]/_components/EventCard.tsx
  app/(route)/artist/[artistId]/page.tsx
  app/(route)/event/[eventId]/_components/Banner.tsx
  app/(route)/event/[eventId]/_components/KakaoMap.tsx
  app/(route)/event/[eventId]/_components/tab/DescriptionTab.tsx
  app/(route)/mypage/_components/tab/MyCalendarTab/ChipButtons.tsx
  app/(route)/mypage/_components/tab/MyCalendarTab/index.tsx
  app/(route)/mypage/_components/tab/MyLocationTab/index.tsx
  app/(route)/signin/_components/SigninDottedLayout.tsx
  app/(route)/signin/page.tsx
  app/_components/KakaoMap.tsx
  app/_components/header/MobileHeader.tsx
  app/_constants/eventStatus.tsx
  app/_types/index.ts
  app/_types/queryType.ts
  app/layout.tsx
  app/not-found.tsx
  public/image/dotted-signin.png
Labels: ✨feat

#187 ⚡️fix : 토글탭 on/off에 따라 지도 렌더링 영역이 변경되지 않는 오류 해결
  app/(route)/artist/[artistId]/page.tsx
  app/(route)/mypage/_components/tab/MyLocationTab/index.tsx
  app/_components/KakaoMap.tsx
  public/icon/arrow-left_sm.svg
Labels: ⚡️fix

#188 ⚡️fix : 배포 2.0 (지도 오류)
  app/(route)/artist/[artistId]/page.tsx
  app/(route)/mypage/_components/tab/MyLocationTab/index.tsx
  app/_components/KakaoMap.tsx
  public/icon/arrow-left_sm.svg
Labels: ⚡️fix

#189 ✨ feat & 💄design: /mypage 디자인 수정사항 반영 및 추가 기능 구현
  app/(route)/artist/[artistId]/_components/ArtistMap.tsx
  app/(route)/artist/[artistId]/_components/EventCard.tsx
  app/(route)/artist/[artistId]/page.tsx
  app/(route)/mypage/_components/NoContent.tsx
  app/(route)/mypage/_components/UserProfile.tsx
  app/(route)/mypage/_components/tab/MyArtistTab/MyArtistEvent.tsx
  app/(route)/mypage/_components/tab/MyArtistTab/MyArtists.tsx
  app/(route)/mypage/_components/tab/MyArtistTab/index.tsx
  app/(route)/mypage/_components/tab/MyCalendarTab/ChipButtons.tsx
  app/(route)/mypage/_components/tab/MyCalendarTab/MyCalendar.tsx
  app/(route)/mypage/_components/tab/MyCalendarTab/NoContentsInCalendar.tsx
  app/(route)/mypage/_components/tab/MyCalendarTab/index.tsx
  app/(route)/mypage/_components/tab/MyLocationTab/MyKaKaoMap.tsx
  app/(route)/mypage/_components/tab/MyLocationTab/index.tsx
  app/(route)/mypage/_components/tab/MyPostTab.tsx
  app/(route)/mypage/_components/tab/MyReviewTab/MyReview.tsx
  app/(route)/mypage/_components/tab/MyReviewTab/index.tsx
  app/(route)/mypage/page.tsx
  app/(route)/reset-password/_components/ResetSetUp.tsx
  app/(route)/signup/_components/Term.tsx
  app/(route)/signup/_components/step/AccountInfo.tsx
  app/(route)/signup/_components/step/TermsAgreement.tsx
  app/(route)/signup/page.tsx
  app/_api/api.ts
  app/_components/Tabs.tsx
  app/_components/bottom-sheet/ControlMyDataBottomSheet.tsx
  app/_components/button/HeartButton.tsx
  app/_components/button/HeartIcon.tsx
  app/_components/card/HorizontalEventCard.tsx
  app/_components/card/KebabContents.tsx
  app/_components/modal/DeleteEventModal.tsx
  app/_constants/calendarStyle.ts
  app/_constants/toast.ts
  app/_types/deleteBodyType.ts
  app/_types/getResType.ts
  app/_types/index.ts
  app/_types/queryType.ts
  public/icon/heart-inside-circle.svg
  public/icon/kebab.svg
Labels: ✨feat, 🚫 merge, 💄design

#190 💄 design: edit 페이지 pc 반응형 디자인
  app/(route)/event/[eventId]/edit/page.tsx
  app/(route)/post/_components/_inputs/DetailInput.tsx
  app/(route)/post/_components/_inputs/MainInput.tsx
  app/(route)/post/_components/_inputs/StarInput.tsx
  app/(route)/post/_components/_inputs/SubInput.tsx
  app/_components/ArtistCard.tsx
  app/_components/bottom-sheet/BottomSheetMaterial.tsx
  app/_components/bottom-sheet/content/EventTypeList.tsx
  app/_components/input/InputArea.tsx
  app/_components/input/SearchInput.tsx
Labels: 💄design

#192 ⚡️fix & ♻️ refactor : ChipButtons 중복 삭제 및 이름 변경 / 지도 관련 변수들을 묶는 훅
  app/(route)/artist/[artistId]/_components/ArtistMap.tsx
  app/(route)/artist/[artistId]/page.tsx
  app/(route)/mypage/_components/tab/MyCalendarTab/ChipButtons.tsx
  app/(route)/mypage/_components/tab/MyCalendarTab/MyCalendar.tsx
  app/(route)/mypage/_components/tab/MyCalendarTab/index.tsx
  app/(route)/mypage/_components/tab/MyLocationTab/FilteringButton.tsx
  app/(route)/mypage/_components/tab/MyLocationTab/MapInfoBox.tsx
  app/(route)/mypage/_components/tab/MyLocationTab/MyKaKaoMap.tsx
  app/(route)/mypage/_components/tab/MyLocationTab/index.tsx
  app/_components/TimeFilter.tsx
  app/_hooks/useCustomMap.tsx
Labels: ⚡️fix, ♻️ refactor

#194 ⚡️fix : 마이페이지 타임필터 버튼 복구
  app/(route)/mypage/_components/tab/MyCalendarTab/CalendarTimeFilter.tsx
  app/(route)/mypage/_components/tab/MyCalendarTab/index.tsx
  app/_components/KakaoMap.tsx
Labels: ⚡️fix

#193 Ver 2.0 3차(지도 관련 로직 복구)
  app/(route)/artist/[artistId]/_components/ArtistMap.tsx
  app/(route)/artist/[artistId]/page.tsx
  app/(route)/mypage/_components/tab/MyCalendarTab/CalendarTimeFilter.tsx
  app/(route)/mypage/_components/tab/MyCalendarTab/MyCalendar.tsx
  app/(route)/mypage/_components/tab/MyCalendarTab/index.tsx
  app/(route)/mypage/_components/tab/MyLocationTab/FilteringButton.tsx
  app/(route)/mypage/_components/tab/MyLocationTab/MapInfoBox.tsx
  app/(route)/mypage/_components/tab/MyLocationTab/MyKaKaoMap.tsx
  app/(route)/mypage/_components/tab/MyLocationTab/index.tsx
  app/_components/KakaoMap.tsx
  app/_components/TimeFilter.tsx
  app/_hooks/useCustomMap.tsx
Labels: 🆗 merge

#195 🐛 fix: 데이터 0, 1개일 때 지도 리스트 css 수정
  app/(route)/artist/[artistId]/page.tsx
  app/(route)/mypage/_components/tab/MyLocationTab/index.tsx
Labels: ⚡️fix, 🐛 bug

#197 ⚡️fix : 지도 UI QA
  app/(route)/mypage/_components/tab/MyLocationTab/index.tsx
  app/_components/KakaoMap.tsx
Labels: ⚡️fix

#198 Ver 2.0 배포 5차 (지도 UI QA)
  app/(route)/mypage/_components/tab/MyLocationTab/index.tsx
  app/_components/KakaoMap.tsx
Labels: 🆗 merge

#175 ✨ feat: 관리자 페이지 구현 완료 & 메타 태그 재설정
  app/(route)/admin/_components/ArtistReqList.tsx
  app/(route)/admin/_components/EventClaimList.tsx
  app/(route)/admin/_components/EventList.tsx
  app/(route)/admin/_components/OptionList.tsx
  app/(route)/admin/_components/ReviewClaimList.tsx
  app/(route)/admin/page.tsx
  app/(route)/artist/[artistId]/page.tsx
  app/(route)/search/page.tsx
  app/_api/api.ts
  app/_constants/metaTag.ts
  app/_store/index.ts
  app/_store/slice/adminSlice.ts
  app/layout.tsx
  robots.txt
Labels: ✨feat, 🆗 merge

#199 ✨ feat: 아티스트 페이지 바텀 시트 드래그 구현
  app/(route)/artist/[artistId]/_components/MobileTab.tsx
  app/(route)/artist/[artistId]/_components/PcTab.tsx
  app/(route)/artist/[artistId]/_hooks/useArtistSheet.tsx
  app/(route)/artist/[artistId]/page.tsx
  app/(route)/event/[eventId]/_components/Banner.tsx
  app/(route)/mypage/_components/UserProfile.tsx
  app/(route)/mypage/_components/tab/MyReviewTab/MyReview.tsx
  app/(route)/page.tsx
  app/(route)/post/_components/_inputs/MainInput.tsx
  app/(route)/post/_components/_inputs/StarInput.tsx
  app/(route)/search/_components/Filter.tsx
  app/(route)/search/_hooks/useSearch.tsx
  app/_components/bottom-sheet/BottomSheetMaterial.tsx
  app/_components/bottom-sheet/EventBottomSheet.tsx
  app/_components/card/HorizontalEventCard.tsx
  app/_components/header/PcHeader.tsx
  app/_components/input/SearchInput.tsx
  app/_hooks/useBottomSheet.tsx
  app/_hooks/useCustomMap.tsx
Labels: ✨feat

#201 🐛 bug: 아티스트 지도 모바일 스크롤 문제 해결
  app/(route)/artist/[artistId]/_components/MobileTab.tsx
  app/(route)/artist/[artistId]/_components/PcTab.tsx
  app/(route)/artist/[artistId]/_hooks/useArtistSheet.tsx
  app/(route)/artist/[artistId]/page.tsx
  app/_hooks/useCustomMap.tsx
Labels: 🐛 bug

#203 ⚡️ fix: 아티스트 드래그 UI 수정
  app/(route)/artist/[artistId]/_hooks/useArtistSheet.tsx
  app/(route)/artist/[artistId]/page.tsx
Labels: ⚡️fix

#209 ⚡️ fix(SearchArtist.tsx): 회원가입 아티스트 버튼 안눌리는 문제 해결
  app/(route)/signup/_components/SearchArtist.tsx
Labels: ⚡️fix
