Repository P1Z7/frontend, pull requests merged in 2024-02, with the labels that each got.

#34 ✨ feat: button, HeartButton, ArtistCard 공통 컴포넌트 제작
  app/(route)/mypage/_components/tab/ArtistTab.tsx
  app/(route)/signup/_components/SearchArtist.tsx
  app/(route)/signup/_components/step/MyArtistsInfo.tsx
  app/_components/ArtistCard.tsx
  app/_components/button/HeartButton.tsx
  app/_components/button/index.tsx
  app/_hooks/useFunnel.tsx
  public/icon/heart.svg
  public/image/no-profile.png
Labels: ✨feat, 🆗 merge

#39 🩹 chore: ArtistCard 컴포넌트 width 수정
  app/_components/ArtistCard.tsx
  app/_components/button/index.tsx
Labels: 🩹 chore

#40 💄 design: 캘린더 디자인 완료
  app/_components/modal/CalendarModal.tsx
  app/_constants/calendarStyle.ts
  app/_styles/customCalendar.css
  tsconfig.json
Labels: 🆗 merge

#41 ✨ feat: gnb, top app bar, bottom app bar, 세로형 카드 구현
  app/(route)/_components/BottomNav.tsx
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/(route)/event/[id]/_components/BottomDoubleButton.tsx
  app/(route)/event/[id]/_components/Header.tsx
  app/(route)/event/[id]/_components/ReviewButton.tsx
  app/(route)/event/[id]/_components/tabs/ReviewTab.tsx
  app/(route)/event/[id]/edit/_components/EditContent.tsx
  app/(route)/event/[id]/layout.tsx
  app/(route)/event/[id]/page.tsx
  app/(route)/mypage/_components/EventCalendar.tsx
  app/(route)/page.tsx
  app/(route)/post/_components/DetailInfo.tsx
  app/(route)/post/_components/MainInfo.tsx
  app/(route)/post/_components/StarInfo.tsx
  app/(route)/post/_components/SubInfo.tsx
  app/(route)/search/page.tsx
  app/(route)/setting/favorite/page.tsx
  app/(route)/setting/password/page.tsx
  app/(route)/setting/profile/page.tsx
  app/(route)/signup/_components/step/AccountInfo.tsx
  app/(route)/signup/_components/step/MyArtistsInfo.tsx
  app/(route)/signup/_components/step/ProfileInfo.tsx
  app/_components/BottomNav.tsx
  app/_components/Header.tsx
  app/_components/button/BottomButton.tsx
  app/_components/card/EventMockData.ts
  app/_components/card/VerticalEventCard.tsx
  app/_types/index.ts
  public/icon/add-outline.svg
  public/icon/add-outline_black.svg
  public/icon/home.svg
  public/icon/no-profile.svg
  public/icon/search_black.svg
Labels: 🆗 merge, 💄design

#44 🩹 chore: 공통 컴포넌트 layout 적용
  app/(route)/(bottom-nav)/layout.tsx
  app/(route)/(bottom-nav)/mypage/_components/EventCalendar.tsx
  app/(route)/(bottom-nav)/mypage/_components/UserProfile.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/ArtistTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyReviewTab.tsx
  app/(route)/(bottom-nav)/mypage/page.tsx
  app/(route)/(bottom-nav)/page.tsx
  app/(route)/(bottom-nav)/search/page.tsx
  app/(route)/(bottom-nav)/signin/layout.tsx
  app/(route)/(bottom-nav)/signin/page.tsx
  app/(route)/(header)/event/[id]/_components/Banner.tsx
  app/(route)/(header)/event/[id]/_components/BottomDoubleButton.tsx
  app/(route)/(header)/event/[id]/_components/KakaoMap.tsx
  app/(route)/(header)/event/[id]/_components/tabs/DescriptionTab.tsx
  app/(route)/(header)/event/[id]/_components/tabs/LocationTab.tsx
  app/(route)/(header)/event/[id]/_components/tabs/ReviewTab.tsx
  app/(route)/(header)/event/[id]/edit/_components/EditContent.tsx
  app/(route)/(header)/event/[id]/edit/page.tsx
  app/(route)/(header)/event/[id]/page.tsx
  app/(route)/(header)/event/[id]/post/page.tsx
  app/(route)/(header)/layout.tsx
  app/(route)/(header)/my-artist-event/_components/MyArtistEvent.tsx
  app/(route)/(header)/my-artist-event/page.tsx
  app/(route)/(header)/post/_components/DetailInfo.tsx
  app/(route)/(header)/post/_components/FunnelTitle.tsx
  app/(route)/(header)/post/_components/ImageSection.tsx
  app/(route)/(header)/post/_components/MainInfo.tsx
  app/(route)/(header)/post/_components/PostFooter.tsx
  app/(route)/(header)/post/_components/StarInfo.tsx
  app/(route)/(header)/post/_components/SubInfo.tsx
  app/(route)/(header)/post/_components/_inputs/DetailInput.tsx
  app/(route)/(header)/post/_components/_inputs/MainInput.tsx
  app/(route)/(header)/post/_components/_inputs/StarInput.tsx
  app/(route)/(header)/post/_components/_inputs/SubInput.tsx
  app/(route)/(header)/post/page.tsx
  app/(route)/(header)/setting/favorite/page.tsx
  app/(route)/(header)/setting/layout.tsx
  app/(route)/(header)/setting/password/page.tsx
  app/(route)/(header)/setting/profile/page.tsx
  app/(route)/(header)/signup/_components/GenericForm.tsx
  app/(route)/(header)/signup/_components/ProfileSetup.tsx
  app/(route)/(header)/signup/_components/SearchArtist.tsx
  app/(route)/(header)/signup/_components/SignupFunnelTitle.tsx
  app/(route)/(header)/signup/_components/step/AccountInfo.tsx
  app/(route)/(header)/signup/_components/step/MyArtistsInfo.tsx
  app/(route)/(header)/signup/_components/step/ProfileInfo.tsx
  app/(route)/(header)/signup/page.tsx
  app/(route)/event/[id]/_components/Header.tsx
  app/(route)/event/[id]/layout.tsx
  app/(route)/signin/page.tsx
  app/_components/BottomNav.tsx
  app/_components/Header.tsx
  app/_components/Review.tsx
  app/_components/button/BottomButton.tsx
  app/_components/modal/AddressModal.tsx
  app/_components/modal/CalendarModal.tsx
  app/_hooks/useHeaderTitle.tsx
Labels: 🩹 chore

#42 ✨feat: Chip 공통 컴포넌트 완성
  app/(route)/(bottom-nav)/signin/page.tsx
  app/_components/chip/Chip.tsx
  app/_components/chip/ChipButton.tsx
  app/globals.css
  public/icon/close.svg
  tailwind.config.ts
Labels: ✨feat

#47 💄 design: 탭 디자인 구현
  app/_components/Tabs.tsx
Labels: 💄design

#46 💄 design: 가로형 이벤트 카드 디자인 구현
  app/(route)/(bottom-nav)/search/page.tsx
  app/_components/card/HorizontalEventCard.tsx
  app/_components/card/VerticalEventCard.tsx
  app/_types/index.ts
  app/globals.css
Labels: 💄design

#50 ⚡️ fix: 이벤트 타입 및 mock 데이터 통일
  app/(route)/(bottom-nav)/mypage/_components/EventCalendar.tsx
  app/(route)/(bottom-nav)/search/page.tsx
  app/(route)/(header)/my-artist-event/_components/MyArtistEvent.tsx
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/(route)/_components/carousel/NewestEventsCarousel.tsx
  app/(route)/_components/carousel/PopularEventsCarousel.tsx
  app/_components/card/EventMockData.ts
  app/_components/card/HorizontalEventCard.tsx
  app/_components/card/VerticalEventCard.tsx
  app/_constants/mock.ts
  app/_types/index.ts
  app/_utils/formatString.ts
Labels: ⚡️fix

#48 💄 design: 바텀시트 디자인 구현
  app/_components/Header.tsx
  app/_components/bottom-sheet/BigRegionBottomSheet.tsx
  app/_components/bottom-sheet/BottomSheetFrame.tsx
  app/_components/bottom-sheet/BottomSheetMaterial.tsx
  app/_components/bottom-sheet/CalendarBottomSheet.tsx
  app/_components/bottom-sheet/GiftsBottomSheet.tsx
  app/_components/bottom-sheet/MyPageBottomSheet.tsx
  app/_components/bottom-sheet/SmallRegionBottomSheet.tsx
  app/_components/bottom-sheet/StarBottomSheet.tsx
Labels: 💄design

#45 ✨feat: Alert, TextField 공통 컴포넌트 제작
  app/(route)/(bottom-nav)/signin/page.tsx
  app/_components/Alert.tsx
  app/_components/input/InputArea.tsx
  app/_components/input/InputText.tsx
  public/icon/arrow-right_lg.svg
  public/icon/exclamation.svg
Labels: ✨feat, 🆗 merge

#51 ✨ feat: 공통 api 함수 구현 완료
  app/_api/api.ts
  app/_components/bottom-sheet/StarBottomSheet.tsx
  app/_types/reqType.ts
  next.config.mjs
Labels: ✨feat, 🆗 merge

#52 💄 design: 홈페이지 디자인 완성
  app/(route)/(bottom-nav)/page.tsx
  app/(route)/_components/Footer.tsx
  app/(route)/_components/artist-list/ArtistList.tsx
  app/(route)/_components/artist-list/ProfileMockData.ts
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/_components/BottomNav.tsx
  app/_components/Carousel.tsx
  app/_components/artist-list/ArtistProfile.tsx
  app/_components/card/VerticalEventCard.tsx
  public/icon/hero.svg
  public/icon/logo.svg
  tailwind.config.ts
Labels: 🆗 merge, 💄design

#53 💄 design: 행사 상세 페이지 디자인 완성
  app/(route)/(bottom-nav)/mypage/_components/tab/MyReviewTab.tsx
  app/(route)/(bottom-nav)/mypage/page.tsx
  app/(route)/(header)/event/[id]/_components/Banner.tsx
  app/(route)/(header)/event/[id]/_components/KakaoMap.tsx
  app/(route)/(header)/event/[id]/_components/tab/DescriptionTab.tsx
  app/(route)/(header)/event/[id]/_components/tab/LocationTab.tsx
  app/(route)/(header)/event/[id]/_components/tab/ReviewTab.tsx
  app/(route)/(header)/event/[id]/_components/tabs/DescriptionTab.tsx
  app/(route)/(header)/event/[id]/_components/tabs/LocationTab.tsx
  app/(route)/(header)/event/[id]/_components/tabs/ReviewTab.tsx
  app/(route)/(header)/event/[id]/page.tsx
  app/_components/Evaluation.tsx
  app/_components/Review.tsx
  app/_constants/mock.ts
  app/_types/index.ts
  app/_utils/formatString.ts
  public/icon/calendar.svg
  public/icon/gift.svg
  public/icon/instagram.svg
  public/icon/link.svg
  public/icon/map.svg
  public/icon/marker-bottom.svg
  public/icon/marker.svg
  public/icon/party.svg
  public/icon/sad.svg
  public/icon/twitter.svg
  public/icon/user.svg
  public/icon/youtube.svg
Labels: ✨feat, 💄design

#55 💄 design: post 페이지 UI 완성
  app/(route)/(header)/event/[id]/edit/_components/EditContent.tsx
  app/(route)/(header)/post/_components/FunnelTitle.tsx
  app/(route)/(header)/post/_components/_inputs/MainInput.tsx
  app/(route)/(header)/post/_components/_inputs/StarInput.tsx
  app/(route)/(header)/post/_components/_inputs/SubInput.tsx
  app/(route)/(header)/post/page.tsx
  app/(route)/post/_components/DetailInfo.tsx
  app/(route)/post/_components/FunnelTitle.tsx
  app/(route)/post/_components/ImageSection.tsx
  app/(route)/post/_components/MainInfo.tsx
  app/(route)/post/_components/PostFooter.tsx
  app/(route)/post/_components/PostFrame.tsx
  app/(route)/post/_components/StarInfo.tsx
  app/(route)/post/_components/SubInfo.tsx
  app/(route)/post/_components/_inputs/DetailInput.tsx
  app/(route)/post/_components/_inputs/MainInput.tsx
  app/(route)/post/_components/_inputs/StarInput.tsx
  app/(route)/post/_components/_inputs/SubInput.tsx
  app/(route)/post/page.tsx
  app/_api/api.ts
  app/_components/GiftTag.tsx
  app/_components/Header.tsx
  app/_components/WarningCheck.tsx
  app/_components/bottom-sheet/AddressBottomSheet.tsx
  app/_components/bottom-sheet/BottomSheetMaterial.tsx
  app/_components/bottom-sheet/CalendarBottomSheet.tsx
  app/_components/bottom-sheet/EventTypeBottomSheet.tsx
  app/_components/bottom-sheet/StarBottomSheet.tsx
  app/_components/chip/ChipButton.tsx
  app/_components/input/InputArea.tsx
  app/_components/input/InputFile.tsx
  app/_components/input/InputText.tsx
  app/_components/input/SearchInput.tsx
  app/_components/modal/AddressModal.tsx
  app/_components/modal/CalendarModal.tsx
  app/_components/modal/ModalMaterial.tsx
  app/_styles/customCalendar.css
  app/_types/index.ts
  package-lock.json
  package.json
  public/icon/add-file.svg
  public/icon/checkbox-off.svg
  public/icon/checkbox-on.svg
  tailwind.config.ts
Labels: 🆗 merge, 💄design

#56 💄 design: mypage 프로필, 행사, 아티스트 탭 UI
  app/(route)/(bottom-nav)/mypage/_components/EventCalendar.tsx
  app/(route)/(bottom-nav)/mypage/_components/UserProfile.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/ArtistTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/EventTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyReviewTab.tsx
  app/(route)/(bottom-nav)/mypage/page.tsx
  app/(route)/(header)/signup/_components/SearchArtist.tsx
  app/_components/ArtistCard.tsx
  app/_components/button/HeartButton.tsx
  app/_components/card/HorizontalEventCard.tsx
  app/_constants/calendarStyle.ts
  app/_constants/mock.ts
  app/_types/index.ts
  app/_utils/formatString.ts
  app/_utils/sortEventList.ts
  public/icon/arrow-left_lg.svg
  public/icon/arrow-right_lg.svg
  public/image/no-profile.png
Labels: 🚫 merge, 💄design

#58 ⚡️ fix: 컬러 팔레트 수정
  .prettierrc
  app/(route)/post/_components/_inputs/SubInput.tsx
  app/_components/ArtistCard.tsx
  app/_components/BottomNav.tsx
  app/_components/ProgressBar.tsx
  app/_components/bottom-sheet/EventTypeBottomSheet.tsx
  app/_components/button/index.tsx
  app/globals.css
  tailwind.config.ts
Labels: ⚡️fix

#57 ⚡️ fix: Alert모달에서 x버튼 삭제
  app/(route)/(header)/event/[id]/edit/_components/EditContent.tsx
  app/(route)/post/_components/_inputs/MainInput.tsx
  app/_components/bottom-sheet/CalendarBottomSheet.tsx
  app/_components/modal/AddressModal.tsx
  app/_components/modal/AlertModal.tsx
  app/_components/modal/ModalMaterial.tsx
Labels: ⚡️fix, 🆗 merge

#59 💄 design: edit 페이지 UI 완료
  app/(route)/(header)/event/[id]/edit/_components/EditContent.tsx
  app/(route)/(header)/event/[id]/edit/page.tsx
  app/(route)/post/_components/ImageSection.tsx
  app/(route)/post/_components/_inputs/StarInput.tsx
  app/(route)/post/_components/_inputs/SubInput.tsx
  app/_components/input/InputText.tsx
Labels: 🚫 merge, 💄design

#60 ✨ feat: 바텀시트 드래그 기능 구현
  app/(route)/(bottom-nav)/mypage/_components/UserProfile.tsx
  app/(route)/(bottom-nav)/search/page.tsx
  app/(route)/post/_components/_inputs/MainInput.tsx
  app/(route)/post/_components/_inputs/StarInput.tsx
  app/_components/Header.tsx
  app/_components/bottom-sheet/AddressBottomSheet.tsx
  app/_components/bottom-sheet/BigRegionBottomSheet.tsx
  app/_components/bottom-sheet/BottomSheetMaterial.tsx
  app/_components/bottom-sheet/CalendarBottomSheet.tsx
  app/_components/bottom-sheet/EventTypeBottomSheet.tsx
  app/_components/bottom-sheet/GiftsBottomSheet.tsx
  app/_components/bottom-sheet/MyPageBottomSheet.tsx
  app/_components/bottom-sheet/SmallRegionBottomSheet.tsx
  app/_components/bottom-sheet/StarBottomSheet.tsx
  app/_hooks/useBottomSheet.tsx
  app/_types/index.ts
Labels: ✨feat

#64 💄 design: 내 아티스트의 새 행사 전체보기 페이지 디자인
  app/(route)/(header)/my-artist-event/page.tsx
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/(route)/_components/carousel/NewestEventsCarousel.tsx
  app/(route)/_components/carousel/PopularEventsCarousel.tsx
  app/_hooks/useHeaderTitle.tsx
  public/icon/hero.svg
Labels: 🆗 merge, 🩹 chore, 💄design

#61 💄 design: setting 페이지들 디자인 완료
  app/(route)/(header)/setting/favorite/page.tsx
  app/(route)/(header)/setting/layout.tsx
  app/(route)/(header)/setting/password/page.tsx
  app/(route)/(header)/setting/profile/page.tsx
  app/_components/MyArtistList.tsx
  app/_components/chip/ChipButton.tsx
  app/_components/input/InputProfileImg.tsx
  app/_components/input/InputText.tsx
  app/_components/input/SearchInput.tsx
  app/_components/modal/ModalMaterial.tsx
  public/icon/pencil.svg
  public/icon/search.svg
Labels: 🆗 merge, 💄design

#62 ✨feat: /mypage 행사 탭 '지도 보기' 탭 구현 및 디자인
  app/(route)/(bottom-nav)/mypage/_components/EventTabs.tsx
  app/(route)/(bottom-nav)/mypage/_components/MyKaKaoMap.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/ArtistTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyArtistTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyEventTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyLocationTab.tsx
  app/(route)/(bottom-nav)/mypage/page.tsx
  app/_components/bottom-sheet/LocationDetailBottomSheet.tsx
  app/_components/bottom-sheet/MyPageBottomSheet.tsx
  app/_components/button/index.tsx
  app/_components/card/HorizontalEventCard.tsx
  app/_constants/calendarStyle.ts
Labels: ✨feat, 🆗 merge

#67 🩹 chore: 행사 상세 설명 위치 및 디자인 수정
  app/(route)/(header)/event/[id]/_components/tab/DescriptionTab.tsx
Labels: 🩹 chore

#70 ♻️ refactor: api함수 타입 자동 추론되도록 수정
  app/_api/api.ts
  app/_components/bottom-sheet/StarBottomSheet.tsx
  app/_types/queryType.ts
  app/_types/reqPostType.ts
Labels: ♻️ refactor

#68 ✨ feat: 캘린더에 표시되는 행사 기간 UI 비즈니스 로직 수정
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab.tsx
  app/(route)/(header)/setting/favorite/page.tsx
  app/_components/MyArtistList.tsx
  app/_components/chip/ChipButton.tsx
  app/_components/input/InputText.tsx
  app/_components/modal/InputModal.tsx
Labels: ✨feat, ⚡️fix, 🆗 merge

#71 fix : ChipButton, InputText
  app/(route)/(header)/setting/favorite/page.tsx
  app/_components/MyArtistList.tsx
  app/_components/chip/ChipButton.tsx
  app/_components/input/InputText.tsx
  app/_components/modal/InputModal.tsx
Labels: ⚡️fix, 🆗 merge

#66 💄 design: 검색 페이지 UI 완성
  app/(route)/(bottom-nav)/search/page.tsx
  app/_components/bottom-sheet/BottomSheetMaterial.tsx
  app/_components/bottom-sheet/GiftsBottomSheet.tsx
  app/_components/card/HorizontalEventCard.tsx
  public/icon/arrow-down_sm.svg
Labels: 💄design

#72 feat: InputText, InputArea "isEdit"에 따라 수정메시지 출력
  app/(route)/post/_components/_inputs/MainInput.tsx
  app/_components/input/InputArea.tsx
  app/_components/input/InputText.tsx
Labels: ✨feat

#69 ✨ feat: post 페이지 api 연결 완료
  app/(route)/(header)/event/[id]/edit/_components/EditContent.tsx
  app/(route)/(header)/event/[id]/edit/page.tsx
  app/(route)/(header)/signup/_components/GenericForm.tsx
  app/(route)/post/_components/DetailInfo.tsx
  app/(route)/post/_components/ImageSection.tsx
  app/(route)/post/_components/MainInfo.tsx
  app/(route)/post/_components/StarInfo.tsx
  app/(route)/post/_components/_inputs/DetailInput.tsx
  app/(route)/post/_components/_inputs/MainInput.tsx
  app/(route)/post/_components/_inputs/StarInput.tsx
  app/(route)/post/_components/_inputs/SubInput.tsx
  app/(route)/post/page.tsx
  app/_api/api.ts
  app/_components/ArtistList.tsx
  app/_components/bottom-sheet/StarBottomSheet.tsx
  app/_components/input/SearchInput.tsx
  app/_constants/data.ts
  app/_hooks/useFetchMember.ts
  app/_hooks/useSearch.tsx
  app/_types/postBodyType.ts
  public/icon/search.svg
Labels: ✨feat, 🆗 merge

#74 ⚡️ fix: Chip css 수정
  app/_components/chip/Chip.tsx
Labels: ⚡️fix

#63 💄 design: signup 페이지 UI / SearchArtist 공통 UI
  app/(route)/(header)/event/[id]/edit/page.tsx
  app/(route)/(header)/signup/_components/SearchArtist.tsx
  app/(route)/post/page.tsx
  app/(route)/signup/_components/ProfileSetup.tsx
  app/(route)/signup/_components/SignupFunnelTitle.tsx
  app/(route)/signup/_components/step/AccountInfo.tsx
  app/(route)/signup/_components/step/MyArtistsInfo.tsx
  app/(route)/signup/_components/step/ProfileInfo.tsx
  app/(route)/signup/page.tsx
  app/_components/ArtistCard.tsx
  app/_components/GenericFormProvider.tsx
  app/_components/SearchArtist.tsx
  app/_components/chip/ChipButton.tsx
  app/_components/input/SearchInput.tsx
  app/_components/modal/ReqNewArtistModal.tsx
  app/_utils/signupValidation.ts
Labels: 🆗 merge, 💄design

#79 ✨feat & 💄design : 로그인 페이지 기능, 디자인, 애니메이션 구현
  app/(route)/(bottom-nav)/signin/_components/Confetti.tsx
  app/(route)/(bottom-nav)/signin/_components/LoadingDot.tsx
  app/(route)/(bottom-nav)/signin/layout.tsx
  app/(route)/(bottom-nav)/signin/page.tsx
  app/(route)/signup/page.tsx
  app/_api/api.ts
  app/_api/auth/[...nextauth]/route.ts
  app/_components/GenericFormProvider.tsx
  app/_components/bottom-sheet/StarBottomSheet.tsx
  app/_components/button/ConfettiButton.tsx
  app/_components/input/InputText.tsx
  app/_providers/AuthProvider.tsx
  app/layout.tsx
  package-lock.json
  package.json
  public/icon/closed-eyes_gray.svg
  public/icon/logo_google.svg
  public/icon/logo_kakao.svg
  public/icon/logo_naver.svg
  public/icon/opened-eyes_gray.svg
  public/icon/x_gray.svg
  tsconfig.json
Labels: ✨feat, 💄design

#77 ♻️ refactor: post submit 관련 함수 util로 분리
  app/(route)/post/_components/ImageSection.tsx
  app/(route)/post/_components/_inputs/DetailInput.tsx
  app/(route)/post/_components/_inputs/MainInput.tsx
  app/(route)/post/_components/_inputs/StarInput.tsx
  app/(route)/post/page.tsx
  app/(route)/signup/page.tsx
  app/_components/GenericFormProvider.tsx
  app/_components/bottom-sheet/StarBottomSheet.tsx
  app/_components/input/InputText.tsx
  app/_hooks/useFetchMember.ts
  app/_utils/changeImgUrl.ts
  app/_utils/handleEnterDown.ts
  app/_utils/submitPost.ts
Labels: ♻️ refactor

#76 ✨ feat: 홈페이지 api 연결
  app/(route)/_components/artist-list/ArtistList.tsx
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/(route)/_components/carousel/NewestEventsCarousel.tsx
  app/(route)/_components/carousel/PopularEventsCarousel.tsx
  app/_components/ArtistCard.tsx
  app/_components/button/HeartButton.tsx
  app/_components/card/VerticalEventCard.tsx
  app/_components/chip/Chip.tsx
  app/_types/getResType.ts
  app/_types/index.ts
  tsconfig.json
Labels: ✨feat, 🆗 merge

#78 ✨ feat: 행사 상세 페이지 api 연결
  app/(route)/(header)/event/[eventId]/_components/Banner.tsx
  app/(route)/(header)/event/[eventId]/_components/BottomButton.tsx
  app/(route)/(header)/event/[eventId]/_components/BottomDoubleButton.tsx
  app/(route)/(header)/event/[eventId]/_components/EventReview.tsx
  app/(route)/(header)/event/[eventId]/_components/KakaoMap.tsx
  app/(route)/(header)/event/[eventId]/_components/tab/DescriptionTab.tsx
  app/(route)/(header)/event/[eventId]/_components/tab/LocationTab.tsx
  app/(route)/(header)/event/[eventId]/_components/tab/ReviewTab.tsx
  app/(route)/(header)/event/[eventId]/edit/_components/EditContent.tsx
  app/(route)/(header)/event/[eventId]/edit/page.tsx
  app/(route)/(header)/event/[eventId]/page.tsx
  app/(route)/(header)/event/[eventId]/post/page.tsx
  app/(route)/(header)/event/[id]/_components/Banner.tsx
  app/(route)/(header)/event/[id]/_components/tab/DescriptionTab.tsx
  app/(route)/(header)/event/[id]/_components/tab/ReviewTab.tsx
  app/(route)/(header)/event/[id]/page.tsx
  app/_api/api.ts
  app/_components/Header.tsx
  app/_components/Review.tsx
  app/_components/Tabs.tsx
  app/_components/bottom-sheet/EventKebabBottomSheet.tsx
  app/_components/card/Chip.tsx
  app/_components/card/HorizontalEventCard.tsx
  app/_components/card/VerticalEventCard.tsx
  app/_components/modal/ReportModal.tsx
  app/_components/modal/TextModal.tsx
  app/_hooks/useHeaderTitle.tsx
  app/_hooks/useInfiniteScroll.ts
  app/_types/index.ts
  app/_types/postBodyType.ts
  app/_types/queryType.ts
  app/_utils/formatString.ts
Labels: ✨feat

#80 💄 design: 수정요청 페이지 UI 구현
  app/(route)/(header)/event/[eventId]/approve/[editId]/_components/EditBox.tsx
  app/(route)/(header)/event/[eventId]/approve/[editId]/page.tsx
  app/(route)/(header)/event/[eventId]/approve/_components/EditCard.tsx
  app/(route)/(header)/event/[eventId]/approve/_components/ReactionIcon.tsx
  app/(route)/(header)/event/[eventId]/approve/page.tsx
  app/_hooks/useHeaderTitle.tsx
  app/_types/getType.ts
  app/_types/index.ts
  public/icon/edit-approve-disabled.svg
  public/icon/edit-approve.svg
  public/icon/edit-reject-disabled.svg
  public/icon/edit-reject.svg
  public/icon/link.svg
  public/icon/user.svg
Labels: 💄design

#83 ✨ feat: 후기 등록 페이지 api 연결
  .prettierrc
  .vscode/settings.json
  app/(route)/(header)/event/[eventId]/_components/Banner.tsx
  app/(route)/(header)/event/[eventId]/page.tsx
  app/(route)/(header)/event/[eventId]/post/_components/MemoizedImageList.tsx
  app/(route)/(header)/event/[eventId]/post/page.tsx
  app/_api/api.ts
  app/_types/postBodyType.ts
  tsconfig.json
Labels: ✨feat

#85 ✨ feat: signup, SearchArtist api 연결
  app/(route)/(header)/event/[eventId]/_components/Banner.tsx
  app/(route)/(header)/event/[eventId]/_components/tab/ReviewTab.tsx
  app/(route)/(header)/setting/favorite/page.tsx
  app/(route)/_components/artist-list/ArtistList.tsx
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/(route)/_components/carousel/NewestEventsCarousel.tsx
  app/(route)/_components/carousel/PopularEventsCarousel.tsx
  app/(route)/signup/_components/step/AccountInfo.tsx
  app/(route)/signup/_components/step/MyArtistsInfo.tsx
  app/(route)/signup/_components/step/ProfileInfo.tsx
  app/(route)/signup/page.tsx
  app/_api/api.ts
  app/_components/GenericFormProvider.tsx
  app/_components/MyArtistList.tsx
  app/_components/SearchArtist.tsx
  app/_components/button/BottomButton.tsx
  app/_components/button/index.tsx
  app/_components/input/InputText.tsx
  app/_components/input/SearchInput.tsx
  app/_constants/mock.ts
  app/_types/index.ts
  app/_types/postBodyType.ts
  app/_utils/handleSignupSubmit.ts
  app/_utils/signupValidation.ts
  public/image/basil_add-outline.svg
Labels: ✨feat, 🆗 merge

#87 ✨ feat: 검색 페이지 api 연결
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab.tsx
  app/(route)/(bottom-nav)/search/_components/FilterButton.tsx
  app/(route)/(bottom-nav)/search/_components/SortButton.tsx
  app/(route)/(bottom-nav)/search/page.tsx
  app/(route)/(header)/my-artist-event/_components/MyArtistEvent.tsx
  app/_components/card/HorizontalEventCard.tsx
  app/_components/input/SearchInput.tsx
  app/_constants/data.ts
  app/_types/getResType.ts
  app/_types/queryType.ts
  app/_utils/formatString.ts
  app/_utils/handleQueryString.ts
  public/icon/reset.svg
  tailwind.config.ts
Labels: ✨feat

#88 ✨ feat: 아티스트 둘러보기 무한스크롤 구현
  app/(route)/(header)/event/[eventId]/_components/BottomDoubleButton.tsx
  app/(route)/_components/artist-list/ArtistList.tsx
  app/_components/card/VerticalEventCard.tsx
  app/_types/index.ts
  tailwind.config.ts
Labels: ✨feat

#92 ✨ feat(SearchArtist): 무한스크롤
  app/(route)/signup/_components/SearchArtist.tsx
  app/(route)/signup/_components/step/AccountInfo.tsx
  app/(route)/signup/_components/step/MyArtistsInfo.tsx
Labels: ✨feat, 🆗 merge

#91 ✨ feat & 💄 design /mypage
  app/(route)/(bottom-nav)/mypage/_components/MyKaKaoMap.tsx
  app/(route)/(bottom-nav)/mypage/_components/MyRiew.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyArtistTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyEventTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyLocationTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyReviewTab.tsx
  app/(route)/(bottom-nav)/mypage/page.tsx
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/_api/api.ts
  app/_components/Tabs.tsx
  app/_components/bottom-sheet/BottomSheetMaterial.tsx
  app/_components/bottom-sheet/LocationDetailBottomSheet.tsx
  app/_constants/calendarStyle.ts
  app/_types/index.ts
  app/_types/queryType.ts
  app/_utils/getCalendarTime.ts
  app/_utils/sortEventList.ts
  public/icon/arrow-up_sm.svg
  public/icon/check.svg
Labels: ✨feat, 🆗 merge, 💄design

#93 ✨ feat & 💄 design: 공통 헤더 및 레이아웃, 행사 상세 페이지 데스크탑 디자인
  app/(route)/(bottom-nav)/page.tsx
  app/(route)/(header)/event/[eventId]/_components/Banner.tsx
  app/(route)/(header)/event/[eventId]/_components/BottomButton.tsx
  app/(route)/(header)/event/[eventId]/_components/EventReview.tsx
  app/(route)/(header)/event/[eventId]/_components/tab/DescriptionTab.tsx
  app/(route)/(header)/event/[eventId]/_components/tab/LocationTab.tsx
  app/(route)/(header)/event/[eventId]/_components/tab/ReviewTab.tsx
  app/(route)/(header)/event/[eventId]/page.tsx
  app/(route)/(header)/layout.tsx
  app/(route)/post/page.tsx
  app/_components/BottomNav.tsx
  app/_components/Evaluation.tsx
  app/_components/Tabs.tsx
  app/_components/chip/Chip.tsx
  app/_components/header/MobileHeader.tsx
  app/_components/header/PcHeader.tsx
  app/_components/layout/DottedLayout.tsx
  app/layout.tsx
  public/image/dotted-background.png
  public/image/no-profile.png
Labels: ✨feat, 💄design

#94 🩹 chore: 지역 필터 및 디자인 일부 수정
  app/(route)/(bottom-nav)/search/page.tsx
  app/_components/BottomNav.tsx
  app/_components/Tabs.tsx
  app/_constants/regions.ts
Labels: 🩹 chore

#90 ✨ feat: 수정 요청&승인 페이지 api 연결
  app/(route)/(bottom-nav)/search/page.tsx
  app/(route)/(header)/event/[eventId]/_components/Banner.tsx
  app/(route)/(header)/event/[eventId]/approve/[editId]/_components/EditBox.tsx
  app/(route)/(header)/event/[eventId]/approve/[editId]/page.tsx
  app/(route)/(header)/event/[eventId]/approve/_components/EditCard.tsx
  app/(route)/(header)/event/[eventId]/approve/_components/EditFormat.tsx
  app/(route)/(header)/event/[eventId]/approve/_components/RenderException.tsx
  app/(route)/(header)/event/[eventId]/approve/page.tsx
  app/(route)/(header)/event/[eventId]/edit/_components/EditContent.tsx
  app/_api/api.ts
  app/_components/GenericFormProvider.tsx
  app/_constants/data.ts
  app/_constants/errorMsg.ts
  app/_constants/post.ts
  app/_constants/snsIcon.tsx
  app/_types/getType.ts
  app/_types/index.ts
  app/_types/postBodyType.ts
  app/_types/queryType.ts
  app/_utils/findName.ts
  app/_utils/submitPost.ts
Labels: ✨feat, 🆗 merge

#96 💄 design: 검색 페이지 데스크탑 디자인
  app/(route)/(bottom-nav)/page.tsx
  app/(route)/(bottom-nav)/search/_components/FilterButton.tsx
  app/(route)/(bottom-nav)/search/page.tsx
  app/(route)/(header)/event/[eventId]/_components/Banner.tsx
  app/(route)/(header)/event/[eventId]/_components/BottomButton.tsx
  app/(route)/(header)/event/[eventId]/_components/EventReview.tsx
  app/(route)/(header)/event/[eventId]/_components/tab/DescriptionTab.tsx
  app/(route)/(header)/event/[eventId]/_components/tab/LocationTab.tsx
  app/(route)/(header)/event/[eventId]/_components/tab/ReviewTab.tsx
  app/_components/BottomNav.tsx
  app/_components/Tabs.tsx
  app/_components/card/HorizontalEventCard.tsx
  app/_components/chip/Chip.tsx
  app/_components/header/MobileHeader.tsx
  app/_components/header/PcHeader.tsx
  app/_components/input/SearchInput.tsx
  app/_components/layout/DottedLayout.tsx
  public/image/dotted-background.png
Labels: 💄design

#97 Feat/homepage desktop design
  app/(route)/(bottom-nav)/page.tsx
  app/(route)/_components/Footer.tsx
  app/(route)/_components/artist-list/ArtistList.tsx
  app/(route)/_components/carousel/Carousel.tsx
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/(route)/_components/carousel/NewestEventsCarousel.tsx
  app/(route)/_components/carousel/PopularEventsCarousel.tsx
  app/_components/ArtistCard.tsx
  app/_components/card/VerticalEventCard.tsx
  public/icon/MainHero.svg
  public/icon/arrow-left_xl.svg
  public/icon/arrow-right_xl.svg
  public/icon/back-arrow_black.svg
  public/image/hero.png
  tailwind.config.ts
Labels: 🆗 merge, 💄design

#98 ✨ feat: 수정페이지 유저id 로직 추가 & 아티스트 무한스크롤
  app/(route)/(header)/event/[eventId]/approve/[editId]/_components/EditBox.tsx
  app/(route)/(header)/event/[eventId]/approve/[editId]/page.tsx
  app/(route)/(header)/event/[eventId]/approve/_components/EditCard.tsx
  app/(route)/(header)/event/[eventId]/approve/_components/EditFormat.tsx
  app/(route)/(header)/event/[eventId]/approve/page.tsx
  app/(route)/(header)/event/[eventId]/edit/_components/EditContent.tsx
  app/(route)/(header)/event/[eventId]/edit/_components/InitButton.tsx
  app/(route)/(header)/event/[eventId]/edit/page.tsx
  app/(route)/post/_components/DetailInfo.tsx
  app/(route)/post/_components/_inputs/DetailInput.tsx
  app/(route)/post/_components/_inputs/MainInput.tsx
  app/(route)/post/_components/_inputs/StarInput.tsx
  app/(route)/post/_components/_inputs/SubInput.tsx
  app/(route)/post/page.tsx
  app/_api/api.ts
  app/_components/ArtistList.tsx
  app/_components/GenericFormProvider.tsx
  app/_components/bottom-sheet/EventTypeBottomSheet.tsx
  app/_components/bottom-sheet/StarBottomSheet.tsx
  app/_components/input/InputArea.tsx
  app/_components/input/InputText.tsx
  app/_constants/errorMsg.ts
  app/_hooks/useFetchGroupSolo.tsx
  app/_hooks/useSearch.tsx
  app/_store/index.ts
  app/_store/slice/writerIdSlice.ts
  app/_types/errorMsgType.ts
  app/_types/index.ts
  app/_utils/submitPost.ts
  app/globals.css
Labels: ✨feat, 🆗 merge

#100 ✨ feat: 데스크탑 레이아웃 구현
  app/(route)/(bottom-nav)/mypage/page.tsx
  app/(route)/(bottom-nav)/page.tsx
  app/(route)/(bottom-nav)/search/page.tsx
  app/(route)/(bottom-nav)/signin/page.tsx
  app/(route)/(header)/event/[eventId]/approve/[editId]/page.tsx
  app/(route)/(header)/event/[eventId]/approve/page.tsx
  app/(route)/(header)/layout.tsx
  app/(route)/(header)/my-artist-event/page.tsx
  app/(route)/event/[eventId]/_components/Banner.tsx
  app/(route)/event/[eventId]/_components/BottomButton.tsx
  app/(route)/event/[eventId]/_components/BottomDoubleButton.tsx
  app/(route)/event/[eventId]/_components/EventReview.tsx
  app/(route)/event/[eventId]/_components/KakaoMap.tsx
  app/(route)/event/[eventId]/_components/tab/DescriptionTab.tsx
  app/(route)/event/[eventId]/_components/tab/LocationTab.tsx
  app/(route)/event/[eventId]/_components/tab/ReviewTab.tsx
  app/(route)/event/[eventId]/approve/[editId]/_components/EditBox.tsx
  app/(route)/event/[eventId]/approve/[editId]/page.tsx
  app/(route)/event/[eventId]/approve/_components/EditCard.tsx
  app/(route)/event/[eventId]/approve/_components/EditFormat.tsx
  app/(route)/event/[eventId]/approve/_components/ReactionIcon.tsx
  app/(route)/event/[eventId]/approve/_components/RenderException.tsx
  app/(route)/event/[eventId]/approve/page.tsx
  app/(route)/event/[eventId]/edit/_components/EditContent.tsx
  app/(route)/event/[eventId]/edit/_components/InitButton.tsx
  app/(route)/event/[eventId]/edit/page.tsx
  app/(route)/event/[eventId]/page.tsx
  app/(route)/event/[eventId]/post/_components/MemoizedImageList.tsx
  app/(route)/event/[eventId]/post/page.tsx
  app/(route)/my-artist-event/_components/MyArtistEvent.tsx
  app/(route)/my-artist-event/page.tsx
  app/(route)/oauth/callback/[provider]/page.tsx
  app/(route)/post/_components/ImageSection.tsx
  app/(route)/post/_components/_inputs/DetailInput.tsx
  app/(route)/post/_components/_inputs/MainInput.tsx
  app/(route)/post/_components/_inputs/StarInput.tsx
  app/(route)/post/_components/_inputs/SubInput.tsx
  app/(route)/post/page.tsx
  app/(route)/setting/favorite/page.tsx
  app/(route)/setting/layout.tsx
  app/(route)/setting/password/page.tsx
  app/(route)/setting/profile/page.tsx
  app/(route)/signup/_components/step/AccountInfo.tsx
  app/(route)/signup/_components/step/ProfileInfo.tsx
  app/(route)/signup/page.tsx
  app/_components/BottomNav.tsx
  app/_components/button/BottomButton.tsx
  app/_components/header/MobileHeader.tsx
  app/_components/header/PcHeader.tsx
  app/_components/input/InputArea.tsx
  app/_components/layout/DottedLayout.tsx
  app/_components/layout/PinkLayout.tsx
  public/image/dotted-background.png
Labels: ✨feat

#101 💄 design: /mypage PC 사이즈
  app/(route)/(bottom-nav)/mypage/_components/EventTabs.tsx
  app/(route)/(bottom-nav)/mypage/_components/MyKaKaoMap.tsx
  app/(route)/(bottom-nav)/mypage/_components/MyRiew.tsx
  app/(route)/(bottom-nav)/mypage/_components/UserProfile.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyArtistTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyEventTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyLocationTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyReviewTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/useMapBox.tsx
  app/(route)/(bottom-nav)/mypage/page.tsx
  app/(route)/signup/_components/step/AccountInfo.tsx
  app/_components/Tabs.tsx
  app/_components/bottom-sheet/BottomSheetMaterial.tsx
  app/_components/bottom-sheet/LocationDetailBottomSheet.tsx
  app/_components/button/HeartButton.tsx
  app/_components/button/HeartIcon.tsx
  app/_components/card/HorizontalEventCard.tsx
  app/_components/card/VerticalEventCard.tsx
  app/_components/layout/DottedLayout.tsx
  app/_constants/calendarStyle.ts
  app/_utils/signupValidation.ts
Labels: 💄design

#103 ⚡️ fix & 💄 design: 데스크탑 헤더 로그인 버튼 추가, 바텀시트 데스크탑 디자인 구현
  app/(route)/(bottom-nav)/search/page.tsx
  app/(route)/event/[eventId]/_components/Banner.tsx
  app/(route)/event/[eventId]/_components/tab/LocationTab.tsx
  app/(route)/event/[eventId]/page.tsx
  app/(route)/event/[eventId]/post/page.tsx
  app/_components/BottomNav.tsx
  app/_components/bottom-sheet/BottomSheetMaterial.tsx
  app/_components/button/HeartIcon.tsx
  app/_components/card/HorizontalEventCard.tsx
  app/_components/header/PcHeader.tsx
  app/_components/modal/ModalMaterial.tsx
Labels: ⚡️fix, 💄design

#102 ✨ feat: 행사 및 후기 좋아요 기능 구현
  app/(route)/event/[eventId]/_components/Banner.tsx
  app/(route)/event/[eventId]/_components/BottomButton.tsx
  app/(route)/event/[eventId]/_components/EventReview.tsx
  app/(route)/event/[eventId]/_components/HeartButton.tsx
  app/(route)/event/[eventId]/_components/tab/ReviewTab.tsx
  app/(route)/event/[eventId]/page.tsx
  app/_components/Review.tsx
  app/_components/card/HorizontalEventCard.tsx
  app/_components/card/VerticalEventCard.tsx
  app/_hooks/useLikeEvent.ts
  app/_types/getResType.ts
  app/_types/index.ts
  app/_types/queryType.ts
Labels: ✨feat

#105 💄 design: /signup pc 사이즈
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/ChipButtons.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/FoldButton.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/MyCalendar.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/NoContentsInCalendar.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/index.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/tileContent.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyLocationTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyLocationTab/FilteringButton.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyLocationTab/MapInfoBox.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyLocationTab/MyKaKaoMap.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyLocationTab/index.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyReviewTab/MyReview.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyReviewTab/index.tsx
  app/(route)/(bottom-nav)/mypage/page.tsx
  app/(route)/signup/_components/SearchArtist.tsx
  app/(route)/signup/_components/SignupFunnelTitle.tsx
  app/(route)/signup/_components/step/AccountInfo.tsx
  app/(route)/signup/_components/step/MyArtistsInfo.tsx
  app/(route)/signup/_components/step/ProfileInfo.tsx
  app/(route)/signup/page.tsx
  app/_api/api.ts
  app/_components/ArtistCard.tsx
  app/_components/button/HeartButton.tsx
  app/_components/card/HorizontalEventCard.tsx
  app/_components/input/SearchInput.tsx
  app/_components/layout/PinkLayout.tsx
  app/_hooks/checkEnterNextButton.tsx
  app/_types/postBodyType.ts
  app/_utils/signupValidation.ts
  app/layout.tsx
  next.config.mjs
  public/image/basil_add-outline.svg
Labels: 🚫 merge, 💄design

#107 ✨ feat: 검색 및 후기 페이지 스켈레톤 UI 구현
  app/(route)/(bottom-nav)/search/page.tsx
  app/(route)/event/[eventId]/_components/Banner.tsx
  app/(route)/event/[eventId]/_components/tab/ReviewTab.tsx
  app/(route)/event/[eventId]/page.tsx
  app/_components/Alert.tsx
  app/_components/layout/DottedLayout.tsx
  app/_components/skeleton/DeferredSuspense.tsx
  app/_components/skeleton/HorizontalEventCardSkeleton.tsx
  app/_components/skeleton/ReviewSkeleton.tsx
  app/_hooks/useInfiniteScroll.ts
  app/_types/getResType.ts
  package-lock.json
  package.json
Labels: ✨feat

#104 💄 design: post & edit & approve pc 디자인 적용
  app/(route)/event/[eventId]/approve/[editId]/page.tsx
  app/(route)/event/[eventId]/approve/page.tsx
  app/(route)/event/[eventId]/edit/_components/EditContent.tsx
  app/(route)/event/[eventId]/edit/page.tsx
  app/(route)/post/_components/DetailInfo.tsx
  app/(route)/post/_components/MainInfo.tsx
  app/(route)/post/_components/PostFrame.tsx
  app/(route)/post/_components/StarInfo.tsx
  app/(route)/post/_components/SubInfo.tsx
  app/(route)/post/_components/_inputs/MainInput.tsx
  app/(route)/post/_components/_inputs/StarInput.tsx
  app/(route)/post/_components/_inputs/SubInput.tsx
  app/(route)/post/page.tsx
  app/_components/ArtistCard.tsx
  app/_components/CheckBox.tsx
  app/_components/WarningCheck.tsx
  app/_components/bottom-sheet/CalendarBottomSheet.tsx
  app/_components/bottom-sheet/EventTypeBottomSheet.tsx
  app/_components/bottom-sheet/StarBottomSheet.tsx
  app/_components/bottom-sheet/content/ArtistContent.tsx
  app/_components/bottom-sheet/content/CalendarContent.tsx
  app/_components/bottom-sheet/content/EventTypeList.tsx
  app/_components/button/BottomButton.tsx
  app/_components/layout/PinkLayout.tsx
  app/_components/modal/AddressModal.tsx
  app/_components/modal/ArtistModal.tsx
  app/_components/modal/CalendarModal.tsx
  app/_components/modal/ModalMaterial.tsx
  app/_hooks/useFetchGroupSolo.ts
  app/_hooks/useGetWindowWidth.ts
  app/_hooks/useHeaderTitle.tsx
  app/_hooks/useModal.ts
  app/_hooks/useNotScroll.ts
  app/_styles/customCalendar.css
  app/_types/index.ts
  app/globals.css
  tailwind.config.ts
Labels: 🚫 merge, 💄design

#108 ⚡️ fix: 후기 등록 로직 수정
  app/(route)/event/[eventId]/post/page.tsx
  app/_api/api.ts
Labels: ⚡️fix

#110 💄 design: /mypage PC 사이즈
  app/(route)/(bottom-nav)/mypage/_components/SettingList.tsx
  app/(route)/(bottom-nav)/mypage/_components/UserProfile.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyArtistTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/MyCalendar.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/index.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/tileContent.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyReviewTab/MyReview.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyReviewTab/index.tsx
  app/(route)/setting/profile/page.tsx
  app/_components/bottom-sheet/MyPageBottomSheet.tsx
  app/_store/session/cookies.ts
Labels: 🆗 merge, 💄design

#106 ✨ feat: 아티스트의 행사 api 연결, 💄 design: 데스크탑 디자인 수정
  app/(route)/_components/Footer.tsx
  app/(route)/_components/carousel/Carousel.tsx
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/(route)/my-artist-event/_components/MyArtistEvent.tsx
  app/(route)/my-artist-event/page.tsx
  app/_api/api.ts
  app/_components/BottomNav.tsx
  app/_types/getResType.ts
  app/_types/queryType.ts
  public/icon/MainHero.svg
  public/icon/hero.svg
  public/image/hero.png
Labels: ✨feat, 🆗 merge, 💄design

#114 ⚡️ hotfix: 후기 좋아요 및 등록 수정
  app/(route)/event/[eventId]/_components/tab/ReviewTab.tsx
  app/(route)/event/[eventId]/post/page.tsx
Labels: ⚡️fix

#115 ⚡️ fix: 좋아요 새로고침 시 바로 반영되도록 수정
  app/_components/button/HeartButton.tsx
  app/_components/card/VerticalEventCard.tsx
Labels: ⚡️fix

#111 ✨feat: 좋아하는 아티스트 API 및 세션 미들웨어 설정
  app/(route)/(bottom-nav)/mypage/_components/SettingList.tsx
  app/(route)/(bottom-nav)/mypage/_components/UserProfile.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/index.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyReviewTab/index.tsx
  app/(route)/(bottom-nav)/mypage/page.tsx
  app/(route)/(bottom-nav)/page.tsx
  app/(route)/(bottom-nav)/search/page.tsx
  app/(route)/(bottom-nav)/signin/page.tsx
  app/(route)/_components/carousel/Carousel.tsx
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/(route)/event/[eventId]/_components/EventReview.tsx
  app/(route)/event/[eventId]/_components/tab/ReviewTab.tsx
  app/(route)/event/[eventId]/approve/[editId]/page.tsx
  app/(route)/event/[eventId]/edit/page.tsx
  app/(route)/my-artist-event/_components/MyArtistEvent.tsx
  app/(route)/oauth/callback/[provider]/page.tsx
  app/(route)/post/_components/_inputs/MainInput.tsx
  app/(route)/post/_components/_inputs/StarInput.tsx
  app/(route)/post/page.tsx
  app/(route)/setting/favorite/page.tsx
  app/(route)/setting/layout.tsx
  app/(route)/setting/password/page.tsx
  app/(route)/setting/profile/page.tsx
  app/(route)/signup/_components/SearchArtist.tsx
  app/(route)/signup/page.tsx
  app/_api/api.ts
  app/_components/BottomNav.tsx
  app/_components/GenericFormProvider.tsx
  app/_components/MyArtistList.tsx
  app/_components/button/HeartButton.tsx
  app/_components/header/MobileHeader.tsx
  app/_components/header/PcHeader.tsx
  app/_components/input/InputProfileImg.tsx
  app/_components/modal/WithdrawModal.tsx
  app/_hooks/useAuth.ts
  app/_hooks/useGetWindowWidth.ts
  app/_hooks/useLikeEvent.ts
  app/_store/session/cookies.ts
  app/_store/session/serverCookies.ts
  app/_types/deleteBodyType.ts
  app/_types/getResType.ts
  app/_types/postBodyType.ts
  app/_utils/serverAuth.ts
  middleware.ts
Labels: ✨feat

#116 ⚡️ fix: 배포 전 수정사항 반영
  app/(route)/(bottom-nav)/mypage/_components/EventTabs.tsx
  app/(route)/(bottom-nav)/mypage/_components/SettingList.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/MyCalendar.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/index.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyReviewTab/MyReview.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyReviewTab/index.tsx
  app/(route)/event/[eventId]/_components/Banner.tsx
  app/(route)/signup/_components/step/AccountInfo.tsx
  app/_api/api.ts
  app/_components/modal/ReportModal.tsx
  app/_components/modal/TextModal.tsx
  app/_types/postBodyType.ts
Labels: ⚡️fix

#118 💄 design: 저녁 QA UI 수정사항 반영
  app/(route)/event/[eventId]/edit/_components/EditContent.tsx
  app/(route)/event/[eventId]/edit/page.tsx
  app/(route)/post/_components/_inputs/MainInput.tsx
  app/(route)/post/_components/_inputs/StarInput.tsx
  app/(route)/post/_components/_inputs/SubInput.tsx
  app/_components/layout/PinkLayout.tsx
Labels: 💄design

#120 💄 design: 라디오버튼 선택 안함 시 bg색 추가
  app/(route)/event/[eventId]/approve/[editId]/page.tsx
  app/(route)/event/[eventId]/edit/_components/EditContent.tsx
  app/(route)/event/[eventId]/edit/page.tsx
  app/(route)/post/_components/PostFrame.tsx
  app/(route)/post/_components/_inputs/SubInput.tsx
  app/_components/GenericFormProvider.tsx
Labels: 💄design

#121 ✨ feat: 후기 신고하기 api 연결
  app/(route)/event/[eventId]/_components/Banner.tsx
  app/(route)/event/[eventId]/_components/EventReview.tsx
  app/_api/api.ts
  app/_components/header/MobileHeader.tsx
  app/_components/modal/ReportModal.tsx
  app/_hooks/useInfScroll.ts
  app/_types/postBodyType.ts
Labels: ✨feat

#122 🩹 chore: GTM 스크립트 추가
  app/_components/Analytics.tsx
  app/layout.tsx
Labels: 🩹 chore

#119 ✨feat: 유저가 진입한 경로에 따른 로그인 후 리다이렉트 + 미들웨어 오류 수정
  app/(route)/(bottom-nav)/mypage/_components/SettingList.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/index.tsx
  app/(route)/(bottom-nav)/signin/page.tsx
  app/(route)/oauth/callback/[provider]/page.tsx
  app/_constants/oauth.ts
  middleware.ts
Labels: ✨feat

#123 ✨ feat: 페이지별 메타태그 설정
  app/(route)/(bottom-nav)/mypage/page.tsx
  app/(route)/(bottom-nav)/page.tsx
  app/(route)/(bottom-nav)/search/page.tsx
  app/(route)/(bottom-nav)/signin/page.tsx
  app/(route)/event/[eventId]/approve/[editId]/page.tsx
  app/(route)/event/[eventId]/approve/page.tsx
  app/(route)/event/[eventId]/edit/page.tsx
  app/(route)/event/[eventId]/page.tsx
  app/(route)/event/[eventId]/post/page.tsx
  app/(route)/my-artist-event/page.tsx
  app/(route)/post/page.tsx
  app/(route)/setting/favorite/page.tsx
  app/(route)/setting/password/page.tsx
  app/(route)/setting/profile/page.tsx
  app/(route)/signup/page.tsx
  app/_components/MetaTag.tsx
  app/_constants/metaTag.ts
  app/layout.tsx
  public/image/meta-thumbnail.png
Labels: ✨feat

#117 ⚡️ fix: 스켈레톤 적용 & 수정사항 반영
  app/(route)/(bottom-nav)/mypage/_components/tab/MyArtistTab.tsx
  app/(route)/_components/artist-list/ArtistList.tsx
  app/(route)/_components/carousel/Carousel.tsx
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/(route)/_components/carousel/NewestEventsCarousel.tsx
  app/(route)/_components/carousel/PopularEventsCarousel.tsx
  app/(route)/my-artist-event/_components/MyArtistEvent.tsx
  app/_components/skeleton/VerticalEventCardSkeleton.tsx
  public/image/gray-hero.png
  public/image/pink-hero.png
Labels: ⚡️fix, 🆗 merge

#126 🩹 chore: css 수정 및 config, image 파일 수정 입니다.
  app/(route)/(bottom-nav)/mypage/_components/tab/MyArtistTab.tsx
  app/(route)/(bottom-nav)/search/page.tsx
  app/(route)/(bottom-nav)/signin/page.tsx
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/(route)/_components/carousel/NewestEventsCarousel.tsx
  app/(route)/_components/carousel/PopularEventsCarousel.tsx
  app/layout.tsx
  next.config.mjs
  public/image/gray-hero.png
  public/image/hero.png
  public/image/pink-hero.png
Labels: 🩹 chore

#127 🩹 chore: 행사 상세 페이지 디자인 및 오타 수정
  app/(route)/(bottom-nav)/mypage/_components/tab/MyArtistTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/ChipButtons.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/index.tsx
  app/(route)/event/[eventId]/_components/Banner.tsx
Labels: 🩹 chore

#129 🩹 chore: 모바일 홈 헤더 높이 수정
  app/(route)/(bottom-nav)/page.tsx
Labels: 🩹 chore

#131 ✨feat : 좋아하는 아티스트 페이지 수정 및, 탭 유지
  app/(route)/(bottom-nav)/mypage/_components/UserProfile.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyArtistTab.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/index.tsx
  app/(route)/(bottom-nav)/mypage/page.tsx
  app/(route)/_components/artist-list/ArtistList.tsx
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/(route)/_components/carousel/NewestEventsCarousel.tsx
  app/(route)/event/[eventId]/page.tsx
  app/(route)/event/[eventId]/post/page.tsx
  app/(route)/setting/my-artist/page.tsx
  app/(route)/signup/_components/SearchArtist.tsx
  app/_components/BottomNav.tsx
  app/_components/MyArtistList.tsx
  app/_components/TabButton.tsx
  app/_components/Tabs.tsx
  app/_components/header/PcHeader.tsx
  app/_constants/metaTag.ts
  app/_hooks/useAuth.ts
  app/_hooks/useHeaderTitle.tsx
  app/_store/mypage-tab/cookies.ts
  next.config.mjs
  package-lock.json
  package.json
Labels: ✨feat

#132 ⚡️hotfix: 이미지 업로드 크기 수정
  app/(route)/(bottom-nav)/mypage/_components/tab/MyArtistTab.tsx
  app/_components/ArtistCard.tsx
  app/_components/card/VerticalEventCard.tsx
Labels: ⚡️fix

#133 🩹 chore(UserProfile): 간단한 코드 수정
  app/(route)/(bottom-nav)/mypage/_components/UserProfile.tsx
Labels: 🩹 chore

#137 🚑Hotfix : 이미지 size 재조정, dynamic import 수정
  app/(route)/(bottom-nav)/mypage/_components/tab/MyArtistTab.tsx
  app/(route)/(bottom-nav)/mypage/page.tsx
  app/(route)/_components/artist-list/ArtistList.tsx
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/(route)/_components/carousel/NewestEventsCarousel.tsx
  app/(route)/_components/carousel/PopularEventsCarousel.tsx
  app/(route)/event/[eventId]/_components/Banner.tsx
  app/(route)/event/[eventId]/_components/tab/DescriptionTab.tsx
  app/(route)/setting/my-artist/page.tsx
  app/_api/api.ts
  app/_components/MyArtistList.tsx
  app/_components/TabButton.tsx
  app/_components/Tabs.tsx
  app/_components/button/HeartButton.tsx
  app/_components/layout/DottedLayout.tsx
  app/_store/tab/cookies.ts
Labels: ⚡️fix

#138 ⚡️ fix & ✨ feat: 좋아요 버튼이 눌렸을 때에만 캐싱 되도록 수정, 검색 결과 수 및 좋아요 수 표시
  app/(route)/(bottom-nav)/mypage/_components/tab/MyReviewTab/MyReview.tsx
  app/(route)/(bottom-nav)/search/page.tsx
  app/(route)/event/[eventId]/_components/Banner.tsx
  app/(route)/event/[eventId]/_components/HeartButton.tsx
  app/(route)/event/[eventId]/page.tsx
  app/_components/card/HorizontalEventCard.tsx
  app/_components/card/VerticalEventCard.tsx
  app/_components/header/MobileHeader.tsx
  app/_hooks/useLikeEvent.ts
  app/_types/index.ts
  app/_types/queryType.ts
Labels: ✨feat, ⚡️fix

#139 ⚡️ fix: 파싱 버그 해결 및 홈페이지 행사 api에 userId 쿼리 추가
  app/(route)/_components/carousel/NewestEventsCarousel.tsx
  app/(route)/_components/carousel/PopularEventsCarousel.tsx
  app/(route)/event/[eventId]/page.tsx
  app/_api/api.ts
  app/_types/queryType.ts
Labels: ⚡️fix

#140 ⚡️ fix: 메타태그 디폴트값 추가 및 행사 상세 페이지 최상단 스크롤
  app/(route)/event/[eventId]/_components/Banner.tsx
  app/(route)/event/[eventId]/page.tsx
Labels: ⚡️fix

#141 ⚡️ fix: 바텀 Nav 관련 간단한 UI 오류 수정, 이벤트 상세 블러이미지 추가
  app/(route)/(bottom-nav)/mypage/_components/tab/MyCalendarTab/index.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyReviewTab/index.tsx
  app/(route)/(bottom-nav)/signin/page.tsx
  app/(route)/event/[eventId]/_components/Banner.tsx
  app/(route)/signup/_components/SearchArtist.tsx
Labels: ⚡️fix

#142 🩹 chore: 디자인 수정
  app/(route)/(bottom-nav)/mypage/_components/UserProfile.tsx
  app/(route)/(bottom-nav)/search/page.tsx
  app/(route)/(bottom-nav)/signin/page.tsx
  app/_components/card/HorizontalEventCard.tsx
  app/_components/header/MobileHeader.tsx
Labels: 🩹 chore

#143 🩹 chore: 탭 위치 수정
  app/_components/Tabs.tsx
Labels: 🩹 chore

#144 ✨ feat: post 실패 시 자동저장 기능 추가 외 수정사항 반영
  app/(route)/post/_components/DetailInfo.tsx
  app/(route)/post/_components/_inputs/MainInput.tsx
  app/(route)/post/_components/_inputs/StarInput.tsx
  app/(route)/post/page.tsx
  app/_components/GenericFormProvider.tsx
  app/_components/PageLoading.tsx
  app/_components/WarningCheck.tsx
  app/_components/bottom-sheet/EventTypeBottomSheet.tsx
  app/_components/bottom-sheet/content/ArtistContent.tsx
  app/_components/bottom-sheet/content/EventTypeList.tsx
  app/_hooks/useFetchGroupSolo.ts
  app/_store/slice/writerIdSlice.ts
  app/layout.tsx
  public/icon/favicon.svg
Labels: ⚡️fix

#145 ✨feat: my-artist 수정페이지 위로가기 버튼 기능 추가,
  app/(route)/(bottom-nav)/mypage/_components/tab/MyArtistTab.tsx
  app/(route)/_components/artist-list/ArtistList.tsx
  app/(route)/_components/carousel/Carousel.tsx
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/(route)/_components/carousel/NewestEventsCarousel.tsx
  app/(route)/_components/carousel/PopularEventsCarousel.tsx
  app/(route)/event/[eventId]/_components/Banner.tsx
  app/(route)/event/[eventId]/_components/tab/DescriptionTab.tsx
  app/(route)/setting/my-artist/page.tsx
  app/_api/api.ts
  app/_components/MyArtistList.tsx
  app/_components/button/HeartButton.tsx
  app/_components/button/ToTopButton.tsx
  app/_components/header/MobileHeader.tsx
  app/_components/header/PcHeader.tsx
  app/_components/layout/PinkLayout.tsx
  public/image/gray-hero.png
  public/image/gray-hero.webp
  public/image/hero.avif
  public/image/hero.png
  public/image/pink-hero.png
  public/image/pink-hero.webp
Labels: ✨feat

#146 🩹 chore: GA id 추가
  app/(route)/(bottom-nav)/signin/page.tsx
Labels: 🩹 chore

#148 ⚡️ hotfix: Banner 이미지 넘침 문제
  app/(route)/event/[eventId]/_components/Banner.tsx
Labels: ⚡️fix, 🆗 merge

#150 ⚡️ hotfix: 아티스트 넘침 문제
  app/_components/card/HorizontalEventCard.tsx
Labels: ⚡️fix

#149 ⚡️ fix: 행사 유형 변경 & 404페이지 추가
  app/(route)/event/[eventId]/edit/_components/EditContent.tsx
  app/_components/GenericFormProvider.tsx
  app/_components/MetaTag.tsx
  app/_components/bottom-sheet/content/EventTypeList.tsx
  app/_components/chip/Chip.tsx
  app/_types/index.ts
  app/layout.tsx
  app/not-found.tsx
  public/icon/logo-underline.svg
  public/image/meta-thumbnail.png
Labels: ⚡️fix

#147 ⚡️ fix(FavArtistEventsCarousel): 내 아티스트의 새 행사 문제 해결
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
Labels: ⚡️fix, 🚫 merge

#152 ✨feat: 좋아하는 아티스트 api 수정
  app/(route)/setting/my-artist/page.tsx
  app/_api/api.ts
  app/_components/MyArtistList.tsx
  app/_components/button/HeartButton.tsx
  app/_components/button/ToTopButton.tsx
  app/_components/header/MobileHeader.tsx
  app/_hooks/useLikeEvent.ts
  app/_types/putBodyType.ts
  public/icon/arrow-up_full.svg
Labels: ✨feat

#153 ⚡️ fix: 내 아티스트 새 행사 캐러셀 로직 및 디자인 수정
  app/(route)/_components/carousel/FavArtistEventsCarousel.tsx
  app/_api/api.ts
  app/_types/queryType.ts
Labels: ⚡️fix

#155 ⚡️fix: 푸터 수정
  app/(route)/_components/Footer.tsx
Labels: ⚡️fix, 💄design

#156 ⚡️ hotfix: 사파리에서 date 호환되도록 수정
  app/_components/bottom-sheet/content/CalendarContent.tsx
Labels: ⚡️fix

#158 ⚡️fix: 닉네임 중복 확인, 상세 페이지 이미지 size UseEffect, 소셜로그인 로직 수정
  app/(route)/event/[eventId]/_components/tab/DescriptionTab.tsx
  app/(route)/oauth/callback/[provider]/page.tsx
  app/(route)/setting/profile/page.tsx
  app/(route)/signup/page.tsx
  app/_api/api.ts
  app/_components/GenericFormProvider.tsx
  app/_components/header/PcHeader.tsx
  app/_components/input/InputText.tsx
  app/_components/modal/WithdrawModal.tsx
  app/_store/session/cookies.ts
  app/_types/queryType.ts
Labels: ⚡️fix

#159 🆗 Main 브랜치 배포 🆗
  app/(route)/event/[eventId]/_components/tab/DescriptionTab.tsx
  app/(route)/oauth/callback/[provider]/page.tsx
  app/(route)/setting/profile/page.tsx
  app/(route)/signup/page.tsx
  app/_api/api.ts
  app/_types/queryType.ts
Labels: 🆗 merge

#160 🩹 fix: 이미지 breakpoint 수정
  app/(route)/event/[eventId]/_components/tab/DescriptionTab.tsx
Labels: 🩹 chore

#161 🆗Main 배포 🆗
  app/(route)/event/[eventId]/_components/tab/DescriptionTab.tsx
Labels: 🆗 merge

#162 💄 design(Footer.tsx): 푸터 디자인 변경사항 반영
  app/(route)/_components/Footer.tsx
Labels: 💄design

#163 ✨feat: 토스트 함수로 분리 / 소셜 로그인 로직 수정 / 닉네임 중복 확인 / 하트버튼 애니메이션
  app/(route)/(bottom-nav)/mypage/_components/SettingList.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyLocationTab/MapInfoBox.tsx
  app/(route)/(bottom-nav)/signin/page.tsx
  app/(route)/event/[eventId]/_components/HeartButton.tsx
  app/(route)/event/[eventId]/_components/tab/LocationTab.tsx
  app/(route)/event/[eventId]/post/page.tsx
  app/(route)/oauth/callback/[provider]/page.tsx
  app/(route)/setting/my-artist/page.tsx
  app/(route)/setting/password/page.tsx
  app/(route)/setting/profile/page.tsx
  app/(route)/signup/_components/SearchArtist.tsx
  app/_api/api.ts
  app/_components/MyArtistList.tsx
  app/_components/button/ConfettiButton.tsx
  app/_components/button/HeartButton.tsx
  app/_components/input/InputProfileImg.tsx
  app/_components/modal/ReportModal.tsx
  app/_components/modal/WithdrawModal.tsx
  app/_constants/confetti.ts
  app/_constants/toast.ts
  app/_hooks/useLikeEvent.ts
  app/_utils/handleSignupSubmit.ts
  app/_utils/toast.ts
Labels: ✨feat

#164 🆗 Main 배포 🆗
  app/(route)/(bottom-nav)/mypage/_components/SettingList.tsx
  app/(route)/(bottom-nav)/mypage/_components/tab/MyLocationTab/MapInfoBox.tsx
  app/(route)/(bottom-nav)/signin/page.tsx
  app/(route)/_components/Footer.tsx
  app/(route)/event/[eventId]/_components/HeartButton.tsx
  app/(route)/event/[eventId]/_components/tab/LocationTab.tsx
  app/(route)/event/[eventId]/approve/[editId]/page.tsx
  app/(route)/event/[eventId]/post/page.tsx
  app/(route)/oauth/callback/[provider]/page.tsx
  app/(route)/setting/my-artist/page.tsx
  app/(route)/setting/password/page.tsx
  app/(route)/setting/profile/page.tsx
  app/(route)/signup/_components/SearchArtist.tsx
  app/_api/api.ts
  app/_components/GenericFormProvider.tsx
  app/_components/MyArtistList.tsx
  app/_components/button/ConfettiButton.tsx
  app/_components/button/HeartButton.tsx
  app/_components/input/InputProfileImg.tsx
  app/_components/modal/ReportModal.tsx
  app/_components/modal/WithdrawModal.tsx
  app/_constants/confetti.ts
  app/_constants/toast.ts
  app/_hooks/useLikeEvent.ts
  app/_utils/handleSignupSubmit.ts
  app/_utils/toast.ts
Labels: 🆗 merge

#167 🐛 : 240224 QA
  app/(route)/(bottom-nav)/signin/page.tsx
  app/(route)/setting/password/page.tsx
  app/(route)/setting/profile/page.tsx
  app/_components/ArtistCard.tsx
  app/_components/MyArtistList.tsx
  app/_components/card/HorizontalEventCard.tsx
  app/_components/card/VerticalEventCard.tsx
Labels: ⚡️fix

#168 🆗Main 배포🆗
  README.md
  app/(route)/(bottom-nav)/signin/page.tsx
  app/(route)/setting/password/page.tsx
  app/(route)/setting/profile/page.tsx
  app/_components/ArtistCard.tsx
  app/_components/MyArtistList.tsx
  app/_components/card/HorizontalEventCard.tsx
  app/_components/card/VerticalEventCard.tsx
Labels: 🆗 merge

#169 ✨ feat: /signup TermsAgreement Step 추가
  app/(route)/signup/_components/PrivacyPolicy.tsx
  app/(route)/signup/_components/ProfileSetup.tsx
  app/(route)/signup/_components/SignupFunnelTitle.tsx
  app/(route)/signup/_components/TermsAndConditions.tsx
  app/(route)/signup/_components/step/TermsAgreement.tsx
  app/(route)/signup/page.tsx
  app/_types/index.ts
Labels: ✨feat, 🆗 merge

#170 🩹 chore: /signup 검색 시 폼 제출되는 것 제한
  app/(route)/signup/_components/ProfileSetup.tsx
  app/_components/input/SearchInput.tsx
Labels: 🩹 chore
